### ISSUE TITLE
2 LofarStMan libs

### ISSUE THREAD

**Issue by CedricDViou** [lofar-astron/LofarStMan#1]
Hello,

We recently encountered some issue when using LofarStMan.
We used this repository and faced some issues that could be 32/64 bits related.
Using the version from the gitlab (https://git.astron.nl/ro/lofar/-/tree/master/LCS/LofarStMan), our problems vanished (see the differences in LofarStMan.h).
Can you confirm what version is to be used, please?

Sincerely Yours,

Cedric (Nançay)

**Comment by aroffringa** [comment]
This should be the latest version -- the one from RO should be removed from the repo at some point. I don't see much differences between the gitlab RO version and this version in terms of headers that could explain the differences you are seeing. What exactly is going wrong with this version?

I did notice that *both* versions don't compile atm with the latest casacore. I've fixed that in https://github.com/lofar-astron/LofarStMan/pull/2 . Maybe that solves your issue?

**Comment by CedricDViou** [comment]
When plotting visibilities, the data get wrong after 2GB of raw data  (between minutes to hours depending on the number of visibilities).
Autocorr end-up with a non-zero imaginary part, some crosscorr get real and this goes on and on with a periodic pattern. 
See plot of the same MS (Amp VS block#) but with the 2 different librairies (left: github, right: svn.astron.nl/LOFAR/tags/LOFAR-Release-4_0_17/LCS/LofarStMan (same that gitlab RO)).
![left: github_lofar-astron  right: svn astron nl_LOFAR-Release-4_0_17_LCS_ ](https://user-images.githubusercontent.com/4154644/92475187-45d6e880-f1dd-11ea-90dc-9d14654364d5.png)

The difference I see between the 2 (3 with svn repo) /include/LofarStMan/LofarStMan.h is present in some integer declarations:
- int / int32
- long / int64
- casacore::uIn / int64

For example:
- `const casacore::Block<int>& ant1() const`  [github](https://github.com/lofar-astron/LofarStMan/blob/master/include/LofarStMan/LofarStMan.h)
- `const casacore::Block<int32>& ant1() const` [gitlab RO](https://git.astron.nl/ro/lofar/-/blob/LOFAR-Release-4_0_17/LCS/LofarStMan/include/LofarStMan/LofarStMan.h)
- `const casacore::Block<int32>& ant1() const` [svn](https://svn.astron.nl/LOFAR/tags/LOFAR-Release-4_0_17/LCS/LofarStMan/include/LofarStMan/LofarStMan.h)

Maybe this is insignificant.  Maybe I just didn't compile the github code correctly.
But only the code from svn or gitlab RO seems to provide us with data that makes sense.
I'm a bit puzzled that the version I "like" better is to be removed.  But there's probably a good reason.
I was hoping you could help me to make it clearer.

**Comment by aroffringa** [comment]
Thanks for the detailed explanation. Indeed you seem to be right; there are incorrect casts in this version of LofarStMan. Not sure why, but my PR #3 should fix it. Could you give a try?

**Comment by CedricDViou** [comment]
Yes, I just compared 61b42c4 and master.
Master looks good now.
Thanks for the fix and the explaination!

**Comment by aroffringa** [comment]
Great, thanks Cedric!
